### ISSUE TITLE
Running bin/solr-instance start results in error

### ISSUE THREAD

**Issue by clt16** [Jarn/collective.solr#15]
After running the buildout to install collective.solr everythiing appears to have installed correctly.  There are two directories in parts for solr-instance and solr-downloads.  Also a bin/solr-instance start script is created.

When I attempt to run bin/solr-instance start, I get the following error:

Traceback (most recent call last):
File "bin/solr-instance", line 110, in <module>
 start(True)
File "bin/solr-instance", line 43, in start
 stdout=logfp, stderr=logfp).pid
File "/usr/local/Plone/Python-2.6/lib/python2.6/subprocess.py", line 633, in **init**
 errread, errwrite)
File "/usr/local/Plone/Python-2.6/lib/python2.6/subprocess.py", line 1139, in _execute_child
 raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by domruf** [comment]
I think since the installation is handled by collective.recipe.solrinstance you should report this issue at https://github.com/collective/collective.recipe.solrinstance/issues

**Comment by hmalinov** [comment]
Most probably java is not installed on your system
